(require :asdf)
(handler-bind ((warning #'muffle-warning)) (ql:quickload "cl-frpc" :silent t))
(defun echo (stream peer) (declare (ignore peer))
  (handler-case (loop for b = (read-byte stream nil :eof) until (eq b :eof)
                      do (write-byte b stream) (force-output stream))
    (error () nil)))
(cl-transport:expose #'echo :backend :frp :server "127.0.0.1" :port 7000 :token "testtoken"
                     :proxy-type "tcp" :remote-port 6000 :tls t :supervise nil)
(sleep 7)
(handler-case
    (let* ((sock (usocket:socket-connect "127.0.0.1" 6000 :element-type '(unsigned-byte 8) :timeout 5))
           (s (usocket:socket-stream sock))
           (msg (sb-ext:string-to-octets "PING-THROUGH-FRP-TUNNEL")))
      (write-sequence msg s) (force-output s)
      (let ((buf (make-array (length msg) :element-type '(unsigned-byte 8))))
        (sb-ext:with-timeout 10 (read-sequence buf s))
        (format t "~&@@ TUNNEL-ECHO ok=~a got=~s~%" (equalp buf msg) (sb-ext:octets-to-string buf))))
  (error (e) (format t "~&@@ CLIENT-ERR: ~a~%" e)))
(sb-ext:exit :code 0)
